[supervisord]
nodaemon=true
user=hindsight
logfile=/dev/stdout
logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:hindsight-api]
command=hindsight-api
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:control-plane]
command=hindsight-control-plane
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PORT="9999",HOSTNAME="0.0.0.0",HINDSIGHT_CP_DATAPLANE_API_URL="http://127.0.0.1:8889",HINDSIGHT_CP_DATAPLANE_API_KEY="%(ENV_HINDSIGHT_API_TENANT_API_KEY)s"
